# Generated by Django 3.2.25 on 2025-05-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_fix_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='services_se_slug_4657d0_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_paid'], name='services_bo_is_paid_06961b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='services_bo_created_3eeec5_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['company_name'], name='services_pr_company_11c036_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['is_verified'], name='services_pr_is_veri_f09ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['is_available'], name='services_pr_is_avai_2529e3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='services_re_created_652f74_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_available'], name='services_se_is_avai_db1380_idx'),
        ),
    ]
