# Generated by Django 3.2.25 on 2025-05-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20250530_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(help_text='Duration in hours'),
        ),
    ]
